{
 "title": "ksqlDB cluster",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,env)"
    }
   },
   {
    "name": "ksqldb_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,ksql_cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_active_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "stat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_running_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Persisted Queries",
   "type": "stat",
   "description": "Num of persisted queries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_persistent_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "stat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries in Error State",
   "type": "stat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Idle Queries",
   "type": "stat",
   "description": "Num of idle queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_idle_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ksql_ksql_metrics_ksql_queries_query_status{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Stopped Queries",
   "type": "stat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Currently Shutting Down Queries",
   "type": "stat",
   "description": "Num of running queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_pending_shutdown_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster liveness",
   "type": "timeseries",
   "description": "Cluster liveness",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_liveness_indicator{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message consumed/sec",
   "type": "timeseries",
   "description": "Message consumed/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_consumed_per_sec{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message produced/sec",
   "type": "timeseries",
   "description": "Message produced/sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ksql_ksql_engine_query_stats_messages_produced_per_sec{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$ksqldb_cluster_id\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"ksqldb\", env=\"$env\",instance=~\"$instance\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"ksqldb\",env=\"$env\",area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Poll Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_avg"
      },
      {}
     ]
    },
    {
     "title": "Poll Latency (Max)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_max"
      }
     ]
    },
    {
     "title": "Process Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_avg"
      }
     ]
    },
    {
     "title": "Process Latency Max",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_max"
      }
     ]
    },
    {
     "title": "Commit Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_avg"
      }
     ]
    },
    {
     "title": "Commit Latency (Max)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_avg"
      }
     ]
    },
    {
     "title": "Punctuate Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_avg"
      }
     ]
    },
    {
     "title": "Punctuate Latency (Max)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}_max"
      }
     ]
    }
   ]
  },
  {
   "title": "StateStore Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Put Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put average latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_avg{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put max latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_max{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put if absent rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put if absent average latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Put if absent max latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Fetch Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_fetch_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Fetch average latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 6, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_fetch_latency_avg{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Fetch max latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_max{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Delete Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Delete average latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 6, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Delete max latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_max{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Restore Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$ksqldb_cluster_id.+\", instance=~\"$instance\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Restore average latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 6, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    },
    {
     "title": "Restore max latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_max{job=\"ksqldb\", thread_id=~\".+$ksqldb_cluster_id.+\"}",
       "legendFormat": "{{thread_id}}"
      }
     ]
    }
   ]
  }
 ]
}